// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fbeuysqpxmmcjfulofjl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZiZXV5c3FweG1tY2pmdWxvZmpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0Mjc5NDAsImV4cCI6MjA2MTAwMzk0MH0.Ic41sR1_SyYPde11vg7zZnkr_DTsGpXN39y5uUCD320";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);